"""Drive one scenario through all five services and render what happened.

The end-to-end demo prints 100+ lines of terminal output. As a capture that is
the weakest asset in the set: the one artifact showing the whole system working
was also the one most truncated to fit.

This produces the same evidence as a page instead. It:

  1. starts all five services
  2. drives one scenario through them, with a fixed request id
  3. reads each service's own event log back over HTTP
  4. renders the joined result to docs/assets/run-report.html
  5. stops the services

**This is a generated report, not a dashboard the system ships.** No service here
serves a UI; they serve JSON. Every value on the page was returned by a service
during the run, and the page is regenerated by running this script -- it cannot
show a result the code did not produce.

The scenario is chosen to need all five: a customer complains about a service that
is degraded, which requires the incident platform to have opened an incident, the
sales engine to value the account, retrieval to ground the reply, and the meeting
service to have indexed something into the same corpus.

    python scripts/render_run_report.py
"""
import html
import json
import os
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WORKSPACE = ROOT.parent
OUTPUT = ROOT / "docs" / "assets" / "run-report.html"

KEY = "portfolio-demo-key"
REQUEST_ID = "run-report-demo"
PORTS = {"rag": 8821, "sales": 8822, "incident": 8823, "ops": 8824, "meeting": 8825}
REPOS = {
    "rag": "enterprise-rag-knowledge-system",
    "sales": "ai-sales-intelligence-engine",
    "incident": "ai-incident-detection-platform",
    "ops": "ai-proactive-customer-operations",
    "meeting": "autonomous-meeting-intelligence",
}
CUSTOMER = "acct_00001"


def base(service):
    return f"http://127.0.0.1:{PORTS[service]}"


def call(method, url, payload=None, request_id=REQUEST_ID, timeout=40):
    body = None if payload is None else json.dumps(payload).encode()
    headers = {"Content-Type": "application/json", "X-API-Key": KEY}
    if request_id:
        headers["X-Request-ID"] = request_id
    request = urllib.request.Request(url, data=body, headers=headers, method=method)
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            return json.loads(response.read().decode()), None
    except urllib.error.HTTPError as error:
        return None, f"HTTP {error.code}"
    except Exception as error:  # noqa: BLE001
        return None, type(error).__name__


def start():
    environment = {
        "rag": {"RETRIEVER": "bm25"},
        "sales": {},
        "incident": {"INCIDENT_MIN_ANOMALIES": "3", "EVENT_SUBSCRIBERS": base("ops"),
                     "EVENT_BACKOFF_SECONDS": "0.5"},
        "ops": {"SALES_API_URL": base("sales"), "INCIDENT_API_URL": base("incident"),
                "RAG_API_URL": base("rag"), "INTEGRATION_TIMEOUT_SECONDS": "3.0"},
        "meeting": {"RAG_API_URL": base("rag")},
    }
    processes = []
    for service, repo in REPOS.items():
        path = WORKSPACE / repo
        if not path.exists():
            raise SystemExit(f"missing repository: {path}")
        # A fresh store per run. Without this a second run appends to the first
        # and the report shows a hop count that never happened in one request --
        # the trace doubled from 18 to 36 exactly this way.
        database = path / "data" / "report.sqlite3"
        database.unlink(missing_ok=True)
        env = {**os.environ, **environment[service], "API_KEY": KEY,
               "INTEGRATION_API_KEY": KEY,
               "APP_DB_PATH": str(database)}
        processes.append(subprocess.Popen(
            [sys.executable, "-m", "uvicorn", "api.server:app", "--host", "127.0.0.1",
             "--port", str(PORTS[service]), "--log-level", "warning"],
            cwd=str(path), env=env,
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        ))
    return processes


def wait_for_all():
    for service in REPOS:
        for _ in range(60):
            data, _ = call("GET", base(service) + "/health", request_id=None, timeout=5)
            if data:
                break
            time.sleep(2)
        else:
            raise SystemExit(f"{service} never became healthy")


def run_scenario():
    """Returns the acts, in the order they happen."""
    acts = []

    # 1. A meeting decision is indexed, so retrieval has something to ground on.
    analysis, error = call("POST", base("meeting") + "/v1/analyze", {
        "meeting_id": "mtg_report",
        "transcript": ("Decision: we will refund customers affected by the checkout "
                       "outage. Priya will publish the incident note by Friday."),
    })
    acts.append({
        "n": 1,
        "title": "A meeting decision becomes searchable knowledge",
        "services": ["meeting", "rag"],
        "detail": "The meeting service extracts decisions and action items, then "
                  "indexes them into the retrieval corpus.",
        "result": analysis or {"error": error},
        "keys": ["decisions", "action_items", "knowledge_publish"],
    })

    # 2. A complaint while nothing is known to be wrong.
    before, error = call("POST", base("ops") + "/v1/decide", {
        "message": "my checkout payment keeps failing and I want my money back",
        "customer_id": CUSTOMER, "service": "checkout",
    })
    acts.append({
        "n": 2,
        "title": "A customer complains -- nothing is known to be wrong yet",
        "services": ["ops", "sales", "incident", "rag"],
        "detail": "Operations enriches from three services before deciding. No "
                  "incident is open, so this is an individual refund.",
        "result": before or {"error": error},
        "keys": ["intent", "sentiment", "policy", "action", "enrichment"],
    })

    # 3. Telemetry degrades until an incident opens and is PUSHED to operations.
    for _ in range(6):
        call("POST", base("incident") + "/v1/score", {
            "service": "checkout", "latency_ms": 5200, "error_count": 40,
            "timeout_count": 12, "traffic_rpm": 480,
            "cpu_percent": 95, "memory_percent": 91,
        })
    time.sleep(5)
    active, error = call("GET", base("incident") + "/v1/incidents/active?service=checkout")
    acts.append({
        "n": 3,
        "title": "Telemetry degrades -- the incident platform opens an incident",
        "services": ["incident"],
        "detail": "The detector scores each minute. Crossing the threshold opens an "
                  "incident and publishes it; delivery is at-least-once.",
        "result": active or {"error": error},
        "keys": ["service", "active", "incident", "rule"],
    })

    # 4. Operations acted on the pushed event without being asked.
    outreach, error = call("GET", base("ops") + "/v1/proactive/outreach")
    acts.append({
        "n": 4,
        "title": "Operations reaches out unprompted -- nobody asked for this",
        "services": ["incident", "ops"],
        "detail": "The only path in the system that starts without a customer. "
                  "Operations recognised the customer from act 2 as affected.",
        "result": outreach or {"error": error},
        "keys": ["batches", "status"],
    })

    # 5. The same complaint, now that the service is known to be degraded.
    after, error = call("POST", base("ops") + "/v1/decide", {
        "message": "my checkout payment keeps failing and I want my money back",
        "customer_id": CUSTOMER, "service": "checkout",
    })
    acts.append({
        "n": 5,
        "title": "The same words, a different decision",
        "services": ["ops", "incident"],
        "detail": "Identical to act 2. The incident is now known, so this is an "
                  "incident response rather than an individual refund -- the "
                  "enrichment changed the outcome.",
        "result": after or {"error": error},
        "keys": ["policy", "action", "enrichment"],
    })
    return acts, before, after


def run_degraded_act(processes):
    """Kill a dependency, then decide anyway.

    Deliberately runs AFTER the trace is collected. Killing the incident service
    first means its events can no longer be read, and the trace silently drops to
    four services -- which happened, and looked like a smaller system rather than
    a stopped process.
    """
    incident_process = processes[list(REPOS).index("incident")]
    incident_process.terminate()
    try:
        incident_process.wait(timeout=15)
    except subprocess.TimeoutExpired:
        incident_process.kill()
    time.sleep(1)

    degraded, error = call("POST", base("ops") + "/v1/decide", {
        "message": "my checkout payment keeps failing and I want my money back",
        "customer_id": CUSTOMER, "service": "checkout",
    })
    return {
        "n": 6,
        "title": "A dependency dies -- the decision is still made",
        "services": ["ops"],
        "detail": "The incident platform was stopped before this call. Operations "
                  "records the failed enrichment in its trace and decides anyway; "
                  "it does not wait, retry forever, or return an error.",
        "result": degraded or {"error": error},
        "keys": ["policy", "action", "enrichment"],
    }



def collect_trace():
    hops = []
    for service in REPOS:
        data, _ = call("GET",
                       f"{base(service)}/v1/events?request_id={REQUEST_ID}&limit=100")
        for event in (data or {}).get("events", []):
            hops.append({"service": service,
                         "event_type": event.get("event_type"),
                         "created_at": event.get("created_at")})
    hops.sort(key=lambda hop: (hop["created_at"] or "", hop["service"]))
    return hops


# Fields whose raw form is unreadable in a table and needs its own summary.
def _enrichment(value):
    """Per-dependency outcome, dropping the explanatory note.

    The note is useful in an API response and is noise in a table -- rendered
    verbatim it truncates mid-sentence, which reads like a broken value rather
    than a long one.
    """
    parts = []
    for name in ("account", "incident", "knowledge"):
        entry = value.get(name)
        if isinstance(entry, dict):
            source = entry.get("source", name)
            parts.append(f"{source}={entry.get('outcome', '?')}")
    return ",  ".join(parts) or "(none)"


def _batches(value):
    if not value:
        return "(none)"
    first = value[0]
    notified = first.get("notified", first.get("customers", "?"))
    return (f"{len(value)} batch(es); latest: "
            f"{first.get('event_type', '?')} on {first.get('service', '?')}, "
            f"notified {notified}")


def summarise(result, keys):
    rows = []
    for key in keys:
        if key not in result:
            continue
        value = result[key]
        if key == "enrichment" and isinstance(value, dict):
            text = _enrichment(value)
        elif key == "batches" and isinstance(value, list):
            text = _batches(value)
        elif isinstance(value, dict):
            if "value" in value:
                text = value["value"]
                if value.get("rule"):
                    text = f"{text}  (rule: {value['rule']})"
            elif "label" in value:
                text = f"{value['label']}"
                if value.get("confidence") is not None:
                    text = f"{text}  ({value['confidence']})"
            elif "type" in value:
                text = value["type"]
            else:
                text = ",  ".join(
                    f"{k}={_short(v)}" for k, v in list(value.items())[:4]
                )
        elif isinstance(value, list):
            text = "; ".join(_short(item) for item in value[:3]) or "(none)"
        else:
            text = str(value)
        rows.append((key, text))
    return rows


def _short(value):
    if isinstance(value, dict):
        for field in ("outcome", "label", "value", "task", "doc_id"):
            if field in value:
                return str(value[field])
        return json.dumps(value)[:60]
    return str(value)[:80]


def render(acts, hops, before, after):
    service_colour = {
        "rag": "#7c9cbf", "sales": "#8fbc8f", "incident": "#d08b7a",
        "ops": "#b39ddb", "meeting": "#89b4b0",
    }

    act_blocks = []
    for act in acts:
        chips = "".join(
            f'<span class="chip" style="--c:{service_colour[s]}">{s}</span>'
            for s in act["services"]
        )
        rows = "".join(
            f'<tr><th>{html.escape(key)}</th>'
            f'<td>{html.escape(str(text))}</td></tr>'
            for key, text in summarise(act["result"], act["keys"])
        )
        act_blocks.append(f'''
    <section class="act">
      <div class="act-head">
        <span class="num">{act['n']}</span>
        <h3>{html.escape(act['title'])}</h3>
        <div class="chips">{chips}</div>
      </div>
      <p class="detail">{html.escape(act['detail'])}</p>
      <table class="kv">{rows}</table>
    </section>''')

    hop_rows = "".join(
        f'<tr><td class="ts">{html.escape(str(hop["created_at"]))}</td>'
        f'<td><span class="chip" style="--c:{service_colour[hop["service"]]}">'
        f'{hop["service"]}</span></td>'
        f'<td class="ev">{html.escape(str(hop["event_type"]))}</td></tr>'
        for hop in hops
    )

    before_policy = (before or {}).get("policy", {}).get("value", "?")
    after_policy = (after or {}).get("policy", {}).get("value", "?")
    services_seen = sorted({hop["service"] for hop in hops})

    return f'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>End-to-end run report</title>
<style>
  :root {{ --ink:#1b2029; --dim:#5c6472; --line:#dfe3e8; --bg:#f7f8f9; }}
  * {{ box-sizing:border-box; }}
  body {{ margin:0; padding:40px; background:var(--bg); color:var(--ink);
         font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif; }}
  .wrap {{ max-width:1120px; margin:0 auto; }}
  h1 {{ font-size:30px; margin:0 0 6px; letter-spacing:-0.02em; }}
  .sub {{ color:var(--dim); margin:0 0 4px; }}
  .note {{ color:var(--dim); font-size:13px; margin:14px 0 28px;
           border-left:3px solid var(--line); padding-left:12px; }}
  .headline {{ display:flex; gap:16px; margin:0 0 28px; flex-wrap:wrap; }}
  .card {{ background:#fff; border:1px solid var(--line); border-radius:10px;
           padding:16px 18px; flex:1; min-width:210px; }}
  .card b {{ display:block; font-size:22px; }}
  .card span {{ color:var(--dim); font-size:13px; }}
  .act {{ background:#fff; border:1px solid var(--line); border-radius:10px;
          padding:18px 20px; margin:0 0 16px; }}
  .act-head {{ display:flex; align-items:center; gap:12px; flex-wrap:wrap; }}
  .num {{ background:var(--ink); color:#fff; width:26px; height:26px;
          border-radius:50%; display:grid; place-items:center;
          font-size:13px; font-weight:700; flex:none; }}
  .act h3 {{ font-size:17px; margin:0; flex:1; }}
  .chips {{ display:flex; gap:6px; flex-wrap:wrap; }}
  .chip {{ background:var(--c); color:#12161c; border-radius:20px;
           padding:2px 10px; font-size:12px; font-weight:600; }}
  .detail {{ color:var(--dim); margin:10px 0 12px; font-size:14px; }}
  table {{ border-collapse:collapse; width:100%; }}
  .kv th {{ text-align:left; width:170px; font-weight:600; color:var(--dim);
            padding:5px 10px 5px 0; vertical-align:top; font-size:13px; }}
  .kv td {{ padding:5px 0; font-family:ui-monospace,Menlo,Consolas,monospace;
            font-size:13px; }}
  .trace {{ background:#fff; border:1px solid var(--line); border-radius:10px;
            padding:18px 20px; }}
  .trace td {{ padding:4px 12px 4px 0; font-size:13px; }}
  .ts {{ color:var(--dim); font-family:ui-monospace,Menlo,Consolas,monospace; }}
  .ev {{ font-family:ui-monospace,Menlo,Consolas,monospace; }}
  h2 {{ font-size:19px; margin:30px 0 12px; }}
</style>
</head>
<body>
<div class="wrap">
  <h1>End-to-end run report</h1>
  <p class="sub">One scenario driven through all five services, request id
     <code>{html.escape(REQUEST_ID)}</code></p>
  <p class="note">
    Generated by <code>scripts/render_run_report.py</code>, which starts the five
    services, drives this scenario, reads each service's own event log back over
    HTTP, and stops them. <strong>This is a report, not a dashboard the system
    ships</strong> &mdash; these services serve JSON, not a UI. Every value below
    was returned by a service during the run.
  </p>

  <div class="headline">
    <div class="card"><b>{len(services_seen)} / 5</b>
      <span>services in the trace</span></div>
    <div class="card"><b>{len(hops)}</b><span>recorded hops, one request id</span></div>
    <div class="card"><b>{html.escape(str(before_policy))} &rarr;
      {html.escape(str(after_policy))}</b>
      <span>same words, different decision</span></div>
  </div>

  <h2>What happened</h2>
  {"".join(act_blocks)}

  <h2>The trace, joined by request id</h2>
  <div class="trace">
    <p class="detail">Each service was asked for the events carrying this request
      id. The identifier crossed every service boundary; storing it beside each
      event is what makes the timeline joinable.</p>
    <table>{hop_rows}</table>
  </div>
</div>
</body>
</html>
'''


def main():
    processes = start()
    try:
        wait_for_all()
        print("five services up")
        acts, before, after = run_scenario()
        hops = collect_trace()          # all five alive, so all five answer
        acts.append(run_degraded_act(processes))
        print(f"scenario complete: {len(hops)} hops across "
              f"{len({h['service'] for h in hops})} services")
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(render(acts, hops, before, after), encoding="utf-8")
        print(f"written: {OUTPUT.relative_to(ROOT)}")
        return 0
    finally:
        for process in processes:
            process.terminate()
        for process in processes:
            try:
                process.wait(timeout=15)
            except subprocess.TimeoutExpired:
                process.kill()
        print("services stopped")


if __name__ == "__main__":
    sys.exit(main())
